language: java

jdk:
  - oraclejdk7
  
script:
  - cd build; mvn verify
  

# whitelist
branches:
  only:
    - master

# send coverage data
after_success:
  - mvn jacoco:report coveralls:report